version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo $FONTAWESOME_TOKEN
      - npm config set @fortawesome:registry https://npm.fontawesome.com/$FONTAWESOME_TOKEN
      - npm install --prefix server
      - npm install --prefix server/client
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build --prefix server/client
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - server/config/*
    - server/index.js
    - server/models/*
    - server/package.json
    - server/routes/*
    - server/services/*
    - server/client/build/*