version: '3'
services:
  mongodb:
        image: mongo:latest
        container_name: "shopperstar-prod"
        environment:
          - MONGO_DATA_DIR: /data/db
          - MONGODB_USER: "${DB_USER}"
          - MONGODB_PASS: "${DB_PASS}" 
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017